name: 'Setup runner'

description: 'Setup self-hosted runner for zksync workflows execution.'

inputs:
  foundry_version:
    type: string
    description: 'Version of foundry to use.'
    required: false
    # Pinned to a specific stable version to avoid breaking changes.
    default: 'v1.5.1'
  zksync_foundry_version:
    type: string
    description: 'Version of zksync-foundry to use.'
    required: false
    # Pinned to a specific stable version to avoid breaking changes.
    default: 'v0.0.30'
  rust_version:
    type: string
    description: 'Version of Rust toolchain to use.'
    required: false
    # Pin to nightly 1.89 version that all our repos are using
    default: 'nightly-2025-05-23'
  enable_cache:
    type: string
    description: 'Whether to enable cache.'
    required: false
    default: 'false'
  save_cache:
    type: string
    description: 'Whether to save cache.'
    required: false
    default: 'false'
  cache_shared_key:
    type: string
    description: 'Shared key for cache.'
    required: false
    default: 'dev'


outputs:
  cache-hit:
    description: 'Whether cache hit.'
    value: ${{ steps.rust-cache.outputs.cache-hit }}


runs:
  using: composite
  steps:

    - name: Install linux packages
      shell: 'bash -ex {0}'
      env:
        DEBIAN_FRONTEND: noninteractive
      if: ${{ runner.os == 'Linux' }}
      run: |
        if command -v sudo >/dev/null 2>&1; then
          SUDO=sudo
        fi
        ${SUDO} apt update && ${SUDO} apt install -y libclang-dev wget jq libssl-dev pkg-config

    - name: Install sccache
      if: ${{ contains(runner.name, 'matterlabs') }}
      shell: 'bash -ex {0}'
      env:
        SCCACHE_VERSION: 'v0.10.0'
        SCCACHE_URL: "https://github.com/mozilla/sccache/releases/download/"
      run: |
        SCCACHE_FILENAME="sccache-${SCCACHE_VERSION}-x86_64-unknown-linux-musl"
        wget --no-verbose "${SCCACHE_URL}/${SCCACHE_VERSION}/${SCCACHE_FILENAME}.tar.gz"
        tar xzf "${SCCACHE_FILENAME}.tar.gz"
        echo "${PWD}/${SCCACHE_FILENAME}" >> "${GITHUB_PATH}"
        export PATH="${PWD}/${SCCACHE_FILENAME}:${PATH}"

    - name: Setup sccache
      if: ${{ contains(runner.name, 'matterlabs') }}
      shell: 'bash -ex {0}'
      run: |
        echo SCCACHE_CACHE_SIZE=50G >> "${GITHUB_ENV}"
        echo SCCACHE_GCS_BUCKET=matterlabs-infra-sccache-storage >> "${GITHUB_ENV}"
        echo SCCACHE_GCS_SERVICE_ACCOUNT=gha-ci-runners@matterlabs-infra.iam.gserviceaccount.com >> "${GITHUB_ENV}"
        echo SCCACHE_ERROR_LOG=/tmp/sccache_log.txt >> "${GITHUB_ENV}"
        echo SCCACHE_GCS_RW_MODE=READ_WRITE >> "${GITHUB_ENV}"
        echo RUSTC_WRAPPER=sccache >> "${GITHUB_ENV}"
        echo SCCACHE_SERVER_PORT=4225 >> "${GITHUB_ENV}"
        sccache --start-server

    - name: Install Rust toolchain
      uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670 # v1.2.2
      env:
        # To fix rate limiting issues with GitHub API
        GITHUB_TOKEN: ${{ github.token }}
      with:
        channel: ${{ inputs.rust_version || 'stable' }}
        inherit-toolchain: true
        components: 'rustfmt,clippy'
        bins: 'cargo-nextest,cargo-llvm-cov'
        cache: false

    - name: Rust cache
      if: inputs.enable_cache == 'true'
      uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
      id: rust-cache
      with:
        shared-key: "${{ inputs.cache_shared_key }}"
        cache-all-crates: true
        cache-workspace-crates: true
        save-if: ${{ inputs.save_cache == 'true' }}

    - name: Install Foundry-ZKsync
      uses: dutterbutter/foundry-zksync-toolchain@v1
      # version should correspond to
      # https://github.com/matter-labs/era-contracts/blob/draft-v31/recompute_hashes.sh#L7
      with:
        version: '${{ inputs.zksync_foundry_version }}'

    - name: Install foundry
      shell: "bash -ex {0}"
      env:
        FOUNDRY_URL: "https://github.com/foundry-rs/foundry/releases/download"
        VERSION: "${{ inputs.foundry_version }}"
        INSTALL_DIR: "foundry"
      run: |
        mkdir "${INSTALL_DIR}"
        curl -LO ${FOUNDRY_URL}/${VERSION}/foundry_${VERSION}_linux_amd64.tar.gz
        tar zxf foundry_${VERSION}_linux_amd64.tar.gz -C ./${INSTALL_DIR}
        chmod +x ./${INSTALL_DIR}/forge ./${INSTALL_DIR}/cast
        echo "${PWD}/${INSTALL_DIR}" >> "${GITHUB_PATH}"
        # Remove forge and cast as they should be used from foundry-zksync
        rm -f ./${INSTALL_DIR}/forge ./${INSTALL_DIR}/cast
        ./${INSTALL_DIR}/anvil --version
        echo "Installed foundry version: ${VERSION}"

    - name: Install uv
      uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0

    - name: Install python
      shell: 'bash -ex {0}'
      run: uv python install

    - name: Install python deps
      shell: 'bash -ex {0}'
      run: uv sync
